import React, { useEffect, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { SessionContext } from '../../context/SessionContext';
import './Processing.css';

const Processing = () => {
  const { processingOption, setSummary } = useContext(SessionContext);
  const navigate = useNavigate();

  useEffect(() => {
    const uploadedFile = sessionStorage.getItem('uploadedFile');
    if (!uploadedFile || !processingOption) {
      navigate('/upload');
      return;
    }

    // Simulate processing delay
    const timer = setTimeout(() => {
      // Fake summary generation based on option
      let fakeSummary = '';
      switch (processingOption) {
        case 'custom-models':
          fakeSummary = 'Summary generated using custom fine-tuned models.';
          break;
        case 'external-apis-parts':
          fakeSummary = 'Summary generated by calling external APIs for each part.';
          break;
        case 'external-api-full':
          fakeSummary = 'Summary generated by sending full paper to external API.';
          break;
        default:
          fakeSummary = 'Summary generated.';
      }
      setSummary(fakeSummary);
      navigate('/results');
    }, 3500);

    return () => clearTimeout(timer);
  }, [processingOption, setSummary, navigate]);

  return (
    <section className="processing-section d-flex flex-column justify-content-center align-items-center py-5">
      <div className="spinner-border text-primary" role="status" aria-label="Loading summary">
        <span className="visually-hidden">Loading...</span>
      </div>
      <h3 className="mt-4" style={{ color: 'var(--primary-color)' }}>Processing your paper...</h3>
    </section>
  );
};

export default Processing;
